/*
 * This source file was generated by the Gradle 'init' task
 */
package solution

import kotlin.test.Test
import kotlin.test.assertNotNull

@Test
fun appHasAGreeting() {
    assertNotNull(main(), "function main() should return Unit")
}
